spring.application.name=ejercicio10-dellamaggiore

# Conexion a PostgreSQL en Render
spring.datasource.url=jdbc:postgresql://dpg-d8kuaknlk1mc73cbtff0-a:5432/bd_prog4_dellamaggiore
spring.datasource.username=bd_prog4_dellamaggiore_user
spring.datasource.password=n2grJFXWL2KkzWlxkJXnGUx0DjtLynP7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
